name: CI

on:
  push:
    branches: [main]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests and collect coverage
      - name: Run tests (tolerate no tests)
        shell: bash
        run: |
          set +e
          pytest --cov --cov-branch --cov-report=xml
          code=$?
          if [ $code -eq 5 ]; then
            echo "No tests found; treating as success."
            exit 0
          else
            exit $code
          fi

      # Step 5: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml  
          fail_ci_if_error: true  # If Codecov fails, fail the CI job

